const $=s=>document.querySelector(s);
const initial={name:'（仮称）〇〇こども園新築工事',start:'2026-11-02',deadline:'2027-09-30',holidays:['2026-11-03','2026-11-23','2026-12-29','2026-12-30','2026-12-31','2027-01-01','2027-01-04','2027-01-11','2027-02-11','2027-02-23','2027-03-22','2027-04-29','2027-05-03','2027-05-04','2027-05-05','2027-07-19','2027-08-11','2027-08-12','2027-08-13'],tasks:[
 ['A','仮設','準備・仮設（仮囲い・事務所）','仮設業者',10,[],0,0,1,4,'近隣あいさつ・測量'],
 ['B','杭','既製杭打ち','杭業者',15,['A'],45,3,1,5,'試験杭を含む'],
 ['C','土工','根切り・山留め','土工業者',10,['B'],1500,150,1,4,'残土の搬出経路'],
 ['D','躯体','基礎躯体（配筋・型枠・打設）','躯体業者',20,['C'],0,0,1,12,'配筋検査'],
 ['E','躯体','1階躯体','躯体業者',20,['D'],0,0,1,12,'打設計画・養生'],
 ['F','躯体','2階・屋根躯体','躯体業者',20,['E'],0,0,1,12,'支保工の存置期間'],
 ['G','防水','屋上防水','防水業者',10,['F'],900,90,1,3,'雨天は作業不可'],
 ['H','外装','外壁・外部建具','外装・建具業者',30,['F'],1200,40,1,6,'建具は長納期'],
 ['I','設備','設備・電気配管（先行）','設備・電気業者',20,['F'],0,0,1,6,'別途工事と調整'],
 ['J','内装','内装仕上げ（LGS・ボード・床・塗装）','内装業者',30,['G','H','I'],0,0,1,10,''],
 ['K','設備','器具付け・試運転','設備・電気業者',15,['J'],0,0,1,4,''],
 ['L','外構','足場解体・外構・園庭','外構業者',25,['J'],0,0,1,6,'遊具・植栽'],
 ['M','検査','検査・手直し・清掃・引渡し','全業者',10,['K','L'],0,0,1,6,'完了検査・消防検査']
].map(([code,trade,name,company,days,deps,quantity,rate,crews,people,notes])=>({code,trade,name,company,days,deps,quantity,rate,crews,people,notes,blocked:[],complete:false}))};
const key='snake_network_schedule_v1';let state;try{state=JSON.parse(localStorage.getItem(key))||structuredClone(initial)}catch{state=structuredClone(initial)}
let result,baseline,delay={code:'',days:0},editing=null;
function save(){localStorage.setItem(key,JSON.stringify(state))}
function iso(d){return d.toISOString().slice(0,10)}
function date(s){return new Date(s+'T12:00:00Z')}
function plus(s,n){let d=date(s);d.setUTCDate(d.getUTCDate()+n);return iso(d)}
function workday(s,blocked=new Set()){const d=date(s).getUTCDay();return d!==0&&d!==6&&!state.holidays.includes(s)&&!blocked.has(s)}
function nthWorkday(index){let d=state.start,count=0,limit=0;while(limit++<3000){if(workday(d)){if(count===index)return d;count++}d=plus(d,1)}throw Error('工期が長すぎます')}
function taskEnd(startIndex,count,blocked){let i=startIndex,done=0,first=null;while(done<count&&i<3000){let day=nthWorkday(i);if(!blocked.includes(day)){if(first===null)first=i;done++}i++}if(done<count)throw Error('工期が長すぎます');return{startIndex:first,endIndex:i}}
function duration(t){let v=t.quantity>0&&t.rate>0?Math.ceil(t.quantity/(t.rate*Math.max(1,t.crews||1))):Number(t.days);if(!Number.isInteger(v)||v<1||v>365)throw Error(`${t.code} の日数を1～365で入力してください`);return v}
function compute(extra={code:'',days:0}){
 const map=new Map(state.tasks.map(t=>[t.code,t]));if(map.size!==state.tasks.length)throw Error('作業記号が重複しています');
 for(const t of state.tasks)for(const p of t.deps){if(!map.has(p))throw Error(`${t.code} の先行作業 ${p} がありません`);if(p===t.code)throw Error(`${t.code} が自分自身に依存しています`)}
 const nodes=new Map();const pending=new Set(map.keys());let order=[];
 while(pending.size){let ready=[...pending].filter(c=>map.get(c).deps.every(d=>nodes.has(d)));if(!ready.length)throw Error('先行作業に循環があります。依存関係を確認してください');
  for(const c of ready){let t=map.get(c),es=Math.max(0,...t.deps.map(d=>nodes.get(d).ef)),d=duration(t)+(c===extra.code?extra.days:0),placement=taskEnd(es,d,t.blocked||[]);nodes.set(c,{...t,d,es,ef:placement.endIndex,actualStart:placement.startIndex,span:placement.endIndex-es,level:t.deps.length?Math.max(...t.deps.map(x=>nodes.get(x).level))+1:0});pending.delete(c);order.push(c)}}
 const total=Math.max(0,...[...nodes.values()].map(n=>n.ef));
 for(const c of order.reverse()){let n=nodes.get(c),following=[...nodes.values()].filter(x=>x.deps.includes(c));n.lf=following.length?Math.min(...following.map(x=>x.ls)):total;n.ls=n.lf-n.span;n.tf=n.ls-n.es;n.ff=following.length?Math.min(...following.map(x=>x.es))-n.ef:total-n.ef;n.startDate=nthWorkday(n.actualStart);n.endDate=nthWorkday(n.ef-1)}
 return{nodes,total,finish:total?nthWorkday(total-1):state.start}
}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function format(s){return s?`${+s.slice(5,7)}/${+s.slice(8,10)}`:'—'}
function render(){try{baseline=compute();result=compute(delay);$('#error').hidden=true}catch(e){$('#error').textContent=e.message;$('#error').hidden=false;return}
 $('#projectName').value=state.name;$('#startDate').value=state.start;$('#deadline').value=state.deadline;$('#holidays').value=state.holidays.join('\n');
 $('#totalDays').textContent=result.total;$('#finishDate').textContent=format(result.finish);let remaining=0,d=plus(result.finish,1);while(d<=state.deadline&&remaining<3000){if(workday(d))remaining++;d=plus(d,1)}let overdue=0;d=plus(state.deadline,1);while(d<=result.finish&&overdue<3000){if(workday(d))overdue++;d=plus(d,1)}$('#margin').textContent=result.finish<=state.deadline?`＋${remaining}`:`−${overdue}`;$('#margin').classList.toggle('negative',result.finish>state.deadline);$('#criticalCount').textContent=[...result.nodes.values()].filter(n=>n.tf===0).length;
 $('#delayTask').innerHTML=state.tasks.map(t=>`<option value="${esc(t.code)}">${esc(t.code)} ${esc(t.name)}</option>`).join('');$('#delayTask').value=delay.code||state.tasks[0]?.code||'';$('#delayDays').value=delay.days;
 renderNetwork();renderCalendar();renderTasks();renderImpact();
}
function renderNetwork(){const nodes=[...result.nodes.values()],levels=Math.max(0,...nodes.map(n=>n.level))+1,w=Math.max(950,levels*270+60),positions=new Map();let maxRows=0;
 for(let level=0;level<levels;level++){let group=nodes.filter(n=>n.level===level);maxRows=Math.max(maxRows,group.length);group.forEach((n,i)=>positions.set(n.code,{x:30+level*270,y:42+i*158}))}
 const height=Math.max(350,maxRows*158+70);let svg=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="context-stroke"/></marker></defs>`;
 for(const n of nodes)for(const d of n.deps){let a=positions.get(d),b=positions.get(n.code),critical=n.tf===0&&result.nodes.get(d).tf===0&&result.nodes.get(d).ef===n.es;svg+=`<path class="edge ${critical?'hot':''}" d="M${a.x+220} ${a.y+49} C${a.x+245} ${a.y+49},${b.x-25} ${b.y+49},${b.x-7} ${b.y+49}" marker-end="url(#arrow)"/>`}
 for(const n of nodes){let p=positions.get(n.code);svg+=`<g class="node ${n.tf===0?'hot':''}" transform="translate(${p.x},${p.y})"><rect width="220" height="108" rx="3"/><text x="14" y="24" class="node-code">${esc(n.code)}　${esc(n.trade)}</text><text x="14" y="49" class="node-name">${esc(n.name.length>15?n.name.slice(0,14)+'…':n.name)}</text><path d="M14 64 H206" class="node-rule"/><text x="14" y="83" class="node-numbers">EST ${n.es}　EFT ${n.ef}</text><text x="14" y="99" class="node-numbers">LST ${n.ls}　LFT ${n.lf}　TF ${n.tf}</text></g>`}
 $('#diagram').setAttribute('viewBox',`0 0 ${w} ${height}`);$('#diagram').setAttribute('width',w);$('#diagram').setAttribute('height',height);$('#diagram').innerHTML=svg;
}
function renderCalendar(){if(!state.tasks.length){$('#calendar').textContent='作業を登録してください';return}let end=plus(result.finish,14);if(state.deadline>end)end=state.deadline;let dates=[],d=state.start;while(d<=end&&dates.length<700){dates.push(d);d=plus(d,1)}const unit=14,width=dates.length*unit,month=[];for(let i=0;i<dates.length;){let m=dates[i].slice(0,7),j=i;while(j<dates.length&&dates[j].startsWith(m))j++;month.push(`<span style="width:${(j-i)*unit}px">${+m.slice(5)}月 <small>${m.slice(0,4)}</small></span>`);i=j}
 let grid=dates.map((x,i)=>`<span class="day ${workday(x)?'':'off'} ${x===iso(new Date())?'today':''}" style="left:${i*unit}px" title="${x}"></span>`).join('');let rows=state.tasks.map(t=>{let n=result.nodes.get(t.code),old=baseline.nodes.get(t.code),start=dates.indexOf(n.startDate),end=dates.indexOf(n.endDate),oldStart=dates.indexOf(old.startDate),oldEnd=dates.indexOf(old.endDate),moved=delay.days&&(oldStart!==start||oldEnd!==end);return `<div class="cal-row"><div class="cal-label"><b>${esc(t.code)}　${esc(t.name)}</b><small>${esc(t.company)} · ${format(n.startDate)}–${format(n.endDate)}</small></div><div class="cal-track" style="width:${width}px">${grid}${moved?`<span class="bar original" style="left:${oldStart*unit}px;width:${(oldEnd-oldStart+1)*unit}px"></span>`:''}<button class="bar ${n.tf===0?'hot':''} ${t.complete?'complete':''}" data-complete="${esc(t.code)}" style="left:${start*unit}px;width:${(end-start+1)*unit}px" title="${esc(t.name)}：${format(n.startDate)}～${format(n.endDate)}。クリックで完了状態を変更">${t.complete?'✓ 完了':n.tf===0?'重要工程':'未完了'}</button></div></div>`}).join('');$('#calendar').innerHTML=`<div class="calendar-inner"><div class="cal-head"><div class="cal-label">工程 / 担当</div><div class="month-line" style="width:${width}px">${month.join('')}</div></div><div class="date-head"><div class="cal-label">日付</div><div class="date-line" style="width:${width}px">${dates.map((x,i)=>`<span class="${workday(x)?'':'off'}" style="left:${i*unit}px" title="${x}">${+x.slice(-2)%5===0?+x.slice(-2):''}</span>`).join('')}</div></div>${rows}</div>`;
}
function renderTasks(){let arr=[...result.nodes.values()].sort((a,b)=>a.es-b.es||a.code.localeCompare(b.code));$('#taskRows').innerHTML=arr.map(n=>`<tr><td><span class="code ${n.tf===0?'hot':''}">${esc(n.code)}</span><br>${esc(n.trade)}</td><td><b>${esc(n.name)}</b><small>${esc(n.company)}</small></td><td>${n.d}日</td><td>${esc(n.deps.join('、')||'なし')}</td><td>${n.es}–${n.ef}</td><td>${n.tf} / ${n.ff}</td><td><button class="status ${n.complete?'done':''}" data-complete="${esc(n.code)}">${n.complete?'✓ 完了':'○ 未完了'}</button></td><td><button class="edit" data-edit="${esc(n.code)}">編集</button></td></tr>`).join('')}
function renderImpact(){if(!delay.days){$('#impactText').textContent='工程を選んで遅れを入力してください。';return}let changes=state.tasks.filter(t=>t.code!==delay.code&&result.nodes.get(t.code).es!==baseline.nodes.get(t.code).es).map(t=>t.name),moved=result.total-baseline.total;$('#impactText').textContent=`${state.tasks.find(t=>t.code===delay.code)?.name||delay.code}が${delay.days}実働日遅れる想定です。${changes.length?`開始が動く工程：${changes.join('、')}。`:'後続工程の開始に変更はありません。'} 全体の完了予定は${moved?`${moved}実働日後ろへ動き、${format(result.finish)}になります。`:'変わりません。'} これは確認用の候補で、元の予定は変更していません。`}
function openEditor(code){editing=code;let t=state.tasks.find(x=>x.code===code)||{code:'',trade:'',name:'',company:'',days:1,quantity:0,rate:0,crews:1,deps:[],blocked:[],notes:''};$('#dialogTitle').textContent=code?`${code} の作業を編集`:'作業を追加';let f=$('#taskForm');for(const k of ['code','trade','name','company','days','quantity','rate','crews','notes'])f.elements[k].value=t[k]??'';f.elements.blocked.value=(t.blocked||[]).join('\n');f.elements.deps.innerHTML=state.tasks.filter(x=>x.code!==code).map(x=>`<option value="${esc(x.code)}" ${t.deps.includes(x.code)?'selected':''}>${esc(x.code)} ${esc(x.name)}</option>`).join('');$('#deleteTask').hidden=!code;$('#taskDialog').showModal()}
function updateState(){save();render()}
$('#projectName').addEventListener('change',e=>{state.name=e.target.value.trim()||initial.name;updateState()});for(const [id,k] of [['startDate','start'],['deadline','deadline']])$(id[0]==='#'?id:'#'+id).addEventListener('change',e=>{if(!e.target.value)return;state[k]=e.target.value;updateState()});
$('#holidays').addEventListener('change',e=>{let dates=e.target.value.split(/[\s,、]+/).filter(Boolean);if(dates.some(x=>!/^\d{4}-\d{2}-\d{2}$/.test(x)||iso(date(x))!==x)){alert('休日は YYYY-MM-DD 形式で入力してください');return}state.holidays=[...new Set(dates)];updateState()});
$('.tabs').addEventListener('click',e=>{let tab=e.target.closest('[data-tab]');if(!tab)return;for(const b of document.querySelectorAll('[data-tab]')){b.removeAttribute('aria-current');$('#'+b.dataset.tab+'View').hidden=true}tab.setAttribute('aria-current','page');$('#'+tab.dataset.tab+'View').hidden=false});
document.addEventListener('click',e=>{let edit=e.target.closest('[data-edit]'),toggle=e.target.closest('[data-complete]');if(edit)openEditor(edit.dataset.edit);if(toggle){let t=state.tasks.find(x=>x.code===toggle.dataset.complete);if(t){t.complete=!t.complete;updateState()}}});
$('#addTask').onclick=()=>openEditor(null);$('#closeDialog').onclick=()=>$('#taskDialog').close();$('#taskForm').onsubmit=e=>{e.preventDefault();let f=e.target,code=f.elements.code.value.trim().toUpperCase(),deps=[...f.elements.deps.selectedOptions].map(x=>x.value),blocked=f.elements.blocked.value.split(/[\s,、]+/).filter(Boolean);if(!code||(!editing&&state.tasks.some(t=>t.code===code))||state.tasks.some(t=>t.code===code&&t.code!==editing)){alert('作業記号を重複しないように入力してください');return}if(blocked.some(x=>!/^\d{4}-\d{2}-\d{2}$/.test(x)||iso(date(x))!==x)){alert('稼働不可日は YYYY-MM-DD 形式で入力してください');return}let t={code,trade:f.elements.trade.value.trim(),name:f.elements.name.value.trim(),company:f.elements.company.value.trim(),days:Number(f.elements.days.value)||1,quantity:Number(f.elements.quantity.value)||0,rate:Number(f.elements.rate.value)||0,crews:Number(f.elements.crews.value)||1,deps,blocked,notes:f.elements.notes.value.trim(),complete:editing?state.tasks.find(x=>x.code===editing).complete:false};let next=structuredClone(state.tasks);if(editing){next[next.findIndex(x=>x.code===editing)]=t;if(code!==editing)next.forEach(x=>{x.deps=x.deps.map(d=>d===editing?code:d)})}else next.push(t);let old=state.tasks;state.tasks=next;try{compute();$('#taskDialog').close();updateState()}catch(error){state.tasks=old;alert(error.message)}};
$('#deleteTask').onclick=()=>{if(!editing)return;if(state.tasks.some(t=>t.deps.includes(editing))){alert('この作業を先行作業として使う工程があります。先に依存関係を編集してください');return}state.tasks=state.tasks.filter(t=>t.code!==editing);$('#taskDialog').close();updateState()};
$('#applyDelay').onclick=()=>{delay={code:$('#delayTask').value,days:Math.max(0,Math.min(365,Math.trunc(Number($('#delayDays').value)||0)))};render()};$('#clearDelay').onclick=()=>{delay={code:'',days:0};render()};$('#print').onclick=()=>window.print();$('#reset').onclick=()=>{if(confirm('この画面の工程を添付資料の初期例に戻しますか？')){state=structuredClone(initial);delay={code:'',days:0};updateState()}};
render();
